default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_list_development

test:
  <<: *default
  database: todo_list_test

production:
  primary: &primary_production
    <<: *default
    database: todo_list_production
    username: todo_list
    password: <%= ENV["TODO_LIST_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: todo_list_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: todo_list_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: todo_list_production_cable
    migrations_paths: db/cable_migrate
